import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Image from "next/image";
import Link from "next/link";
import { getPages } from "@/sanity/sanity-utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Score That!",
  description: "Generated by create Next + Sanity",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const pages = await getPages();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div id="container" className="max-w-7xl mx-auto bg-white px-5 pt-1 pb-10">
          <header className="flex items-center">
              <div className="flex-auto">
                <Link href="/">
                  <Image
                      src="https://scorethat.info/scoring/images/Score_That_icon.png"
                      alt="Score That!"
                      width={135}
                      height={135}
                      className="object-cover rounded-lg ml-5"
                      />
                </Link>
              </div>

              
              {pages.map((page) => (
                <div 
                  key={page._id} 
                  className="flex-initial text-center rounded-lg p-3 hover:bg-blue-700 hover:text-white">
                    <Link
                      href={`/${page.slug}`}
                      className="font-bold" >
                    {page.label}
                    </Link>
                </div>
              ))}
          </header>
          
                      
          {children}
        </div>
      </body>
    </html>
  );
}
